%zewdExtJSData	; Ext-JS Tag Attribute lists
 ;
 ; Product: Enterprise Web Developer (Build 906)
 ; Build Date: Wed, 28 Mar 2012 12:52:00
 ; 
 ; ----------------------------------------------------------------------------
 ; | Enterprise Web Developer for GT.M and m_apache                           |
 ; | Copyright (c) 2004-12 M/Gateway Developments Ltd,                        |
 ; | Reigate, Surrey UK.                                                      |
 ; | All rights reserved.                                                     |
 ; |                                                                          |
 ; | http://www.mgateway.com                                                  |
 ; | Email: rtweed@mgateway.com                                               |
 ; |                                                                          |
 ; | This program is free software: you can redistribute it and/or modify     |
 ; | it under the terms of the GNU Affero General Public License as           |
 ; | published by the Free Software Foundation, either version 3 of the       |
 ; | License, or (at your option) any later version.                          |
 ; |                                                                          |
 ; | This program is distributed in the hope that it will be useful,          |
 ; | but WITHOUT ANY WARRANTY; without even the implied warranty of           |
 ; | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            |
 ; | GNU Affero General Public License for more details.                      |
 ; |                                                                          |
 ; | You should have received a copy of the GNU Affero General Public License |
 ; | along with this program.  If not, see <http://www.gnu.org/licenses/>.    |
 ; ----------------------------------------------------------------------------
 ;
 QUIT
 ;
ColumnModel ;
	;;align
	;;css
	;;dataIndex
	;;editor
	;;fixed:bool
	;;header
	;;hidden:bool
	;;id
	;;listeners
	;;menuDisabled:bool
	;;renderer:ref
	;;resizable:bool
	;;sortable:bool
	;;tooltip
	;;width
	;;***END***
ComboBox ;
	;;allQuery
	;;autoCreate:bool
	;;displayField
	;;editable:bool
	;;forceSelection:bool
	;;handleHeight
	;;hiddenId
	;;hiddenName
	;;lazyInit:bool
	;;lazyRender:bool
	;;listAlign
	;;listClass
	;;listWidth
	;;loadingText
	;;maxHeight
	;;minChars
	;;minListWidth
	;;mode
	;;pageSize
	;;queryDelay
	;;queryParam
	;;resizable:bool
	;;selectOnFocus:bool
	;;selectedClass
	;;shadow:bool
	;;store
	;;title
	;;tpl
	;;transform
	;;triggerAction
	;;triggerClass
	;;typeAhead:bool
	;;typeAheadDelay
	;;valueField
	;;valueNotFoundText
	;;***END*** 
GridPanel
	;;allowDomMove:bool
	;;animCollapse:bool
	;;applyTo
	;;autoExpandColumn
	;;autoExpandMax
	;;autoExpandMin
	;;autoHeight:bool
	;;autoScroll:bool
	;;sutoShow:bool
	;;baseCls
	;;bbar
	;;bodyBorder:bool
	;;bodyStyle
	;;border:bool
	;;buttonAlign
	;;buttons
	;;cls
	;;cm
	;;colModel
	;;collapseFirst:bool
	;;collapsed:bool
	;;collapsedCls:bool
	;;collapsible:bool
	;;columns
	;;contentEl
	;;ctCls
	;;disableSelection:bool
	;;disableClass
	;;draggable:bool
	;;elements
	;;enableColumnHide:bool
	;;enableColumnMove:bool
	;;enableColumnResize:bool
	;;enableDragDrop:bool
	;;enableHdMenu:bool
	;;floating:bool
	;;footer:bool
	;;frame:bool
	;;header:bool
	;;headerAsText:bool
	;;height
	;;hideCollapseTool:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;iconCls
	;;id
	;;keys
	;;listeners
	;;loadMask
	;;maskDisabled:bool
	;;maxHeight
	;;minButtonWidth
	;;minColumnWidth
	;;monitorWindowResize:bool
	;;plugins
	;;renderTo
	;;selModel
	;;shadow
	;;shadowOffset
	;;shim:bool
	;;sm
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;stripeRows:bool
	;;style
	;;tabTip
	;;tbar
	;;title
	;;titleCollapse:bool
	;;tools
	;;trackMouseOver:bool
	;;view
	;;viewConfig
	;;width
	;;***END*** 
HtmlEditor ;
	;;autoShow:bool
	;;clearCls
	;;createLinkText
	;;ctCls
	;;defaultLinkValue
	;;enableAlignments:bool
	;;enableColors:bool
	;;enableFont:bool
	;;enableFontSize:bool
	;;enableFormat:bool
	;;enableLinks:bool
	;;enableLists:bool
	;;enableSourceEdit:bool
	;;fieldLabel
	;;fontFamilies
	;;height
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners
	;;name
	;;pageX
	;;pageY
	;;plugins
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;value
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
Menu ;
	;;allowOtherMenus:bool
	;;defaultAlign
	;;defaults
	;;items
	;;listeners
	;;minWidth
	;;shadow
	;;subMenuAlign
	;;***END*** 
MenuItem ;
	;;activeClass
	;;allowDomMove:bool
	;;applyTo
	;;autoEl
	;;autoShadow:bool
	;;canActivate:bool
	;;checked
	;;checkHandler:ref
	;;cls
	;;ctCls
	;;disabledClass
	;;handler:ref
	;;hideDelay
	;;hideMode
	;;hideOnClick:bool
	;;hideParent:bool
	;;href
	;;hrefTarget
	;;icon
	;;iconCls
	;;id
	;;itemCls
	;;listeners
	;;plugins
	;;renderTo
	;;scope
	;;showDelay
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;text
	;;xtype
	;;***END*** 
Panel ;; Ext.Panel
	;;activeItem
	;;allowDomMove:bool
	;;animCollapse:bool
	;;applyTo
	;;autoDestroy:bool
	;;autoHeight:bool
	;;autoLoad
	;;autoScroll:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;baseCls
	;;bbar
	;;bodyBorder:bool
	;;bodyStyle
	;;border:bool
	;;bufferResize
	;;buttonAlign
	;;buttons
	;;cls
	;;collapseFirst:bool
	;;collapsed:bool
	;;collapsedCls
	;;collapseMode
	;;collapsible:bool
	;;contentEl
	;;ctCls
	;;defaultType
	;;defaults
	;;disabledClass
	;;draggable
	;;el
	;;elements
	;;floating:bool
	;;footer:bool
	;;frame:bool
	;;header:bool
	;;headerAsText:bool
	;;height
	;;hideBorders:bool
	;;hideCollapseTool:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;iconCls
	;;id
	;;items
	;;keys
	;;layout
	;;layoutConfig
	;;listeners
	;;margins
	;;maskDisabled:bool
	;;minButtonWidth
	;;minHeight
	;;minWidth
	;;monitorResize
	;;plugins
	;;region
	;;renderTo
	;;shadow
	;;shadowOffset
	;;shim:bool
	;;split:bool
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabTip
	;;tbar
	;;title
	;;titleCollapse:bool
	;;tools
	;;width
	;;***END***
TabPanel ;
	;;activeItem
	;;activeTab
	;;allowDomMove:bool
	;;animCollapse:bool
	;;animScroll:bool
	;;applyTo
	;;autoDestroy:bool
	;;autoHeight:bool
	;;autoLoad
	;;autoScroll:bool
	;;autoShow:bool
	;;autoTabSelector
	;;autoTabs:bool
	;;autoWidth:bool
	;;baseCls
	;;bbar
	;;bodyBorder:bool
	;;bodyStyle
	;;border:bool
	;;bufferResize:bool
	;;buttonAlign
	;;buttons
	;;cls
	;;collapseFirst:bool
	;;collapsedCls
	;;contentEl
	;;ctCls
	;;defaultType
	;;defaults
	;;deferredRender:bool
	;;disabledClass
	;;draggable:bool
	;;elements
	;;enableTabScroll:bool
	;;floating:bool
	;;footer:bool
	;;frame:bool
	;;height
	;;hideBorders:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;iconCls
	;;id
	;;items
	;;keys
	;;layout
	;;layoutConfig
	;;layoutOnTabChange:bool
	;;listeners
	;;maskDisabled:bool
	;;minButtonWidth
	;;minTabWidth
	;;monitorResize:bool
	;;pageX
	;;pageY
	;;plain:bool
	;;plugins
	;;renderTo
	;;region
	;;resizeTabs:bool
	;;scrollDuration
	;;scrollIncrement
	;;scrollRepeatInterval
	;;shadow:bool
	;;shadowOffset
	;;shim:bool
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabMargin
	;;tabPosition
	;;tabTip
	;;tabWidth
	;;tbar
	;;title
	;;wheelIncrement
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
Toolbar ;
	;;allowDOMMove:bool
	;;applyTo
	;;autoHeight:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;cls
	;;ctCls
	;;disabledClass
	;;height
	;;hideMode
	;;hideParent
	;;id
	;;listeners
	;;pageX
	;;pageY
	;;plugins
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
Viewport ;
	;;activeItem
	;;autoDestroy:bool
	;;autoEl
	;;autoShow:bool
	;;bufferResize:bool
	;;cls
	;;ctCls
	;;defaultType
	;;defaults
	;;disabledClass
	;;hideBorders:bool
	;;id
	;;items
	;;layout
	;;layoutConfig
	;;listeners
	;;monitorResize:bool
	;;pageX
	;;pageY
	;;plugins
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;x
	;;xtype
	;;y
	;;***END***
Store
	;;autoLoad:bool
	;;data
	;;baseParams
	;;listeners
	;;proxy
	;;pruneModifiedRecords:bool
	;;reader
	;;remoteSort:bool
	;;sortInfo
	;;storeId
	;;url
	;;***END***
Window
	;;activeItem
	;;allowDOMMove:bool
	;;animCollapse:bool
	;;animateTarget:bool
	;;applyTo
	;;autoDestroy:bool
	;;autoHeight:bool
	;;autoLoad
	;;autoScroll:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;baseCls
	;;bbar
	;;bodyBorder:bool
	;;bodyStyle
	;;border:bool
	;;bufferResize:bool
	;;buttonAlign
	;;buttons
	;;closable
	;;closeAction
	;;cls
	;;collapseFirst
	;;collapsed:bool
	;;collapsedCls
	;;collapsible:bool
	;;constrain:bool
	;;constrainHeader:bool
	;;contentEl
	;;ctCls
	;;defaultType
	;;defaults
	;;disabledClass
	;;draggable:bool
	;;expandOnShow:bool
	;;footer:bool
	;;header:bool
	;;headerAsText:bool
	;;height
	;;hideBorders:bool
	;;hideCollapseTool:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;iconCls
	;;id
	;;items
	;;keys
	;;layout
	;;layoutConfig
	;;listeners
	;;manager
	;;maskDisabled:bool
	;;maximizable:bool
	;;minButtonWidth
	;;minHeight
	;;minWidth
	;;minimizable:bool
	;;modal:bool
	;;onEsc
	;;pageX
	;;pageY
	;;plain:bool
	;;plugins
	;;renderTo
	;;resizable:bool
	;;resizeHandles
	;;shadow:bool
	;;shadowOffset
	;;shim:bool
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabTip
	;;tbar
	;;title
	;;titleCollapse:bool
	;;tools
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
