%zewdExtJSData	; Ext-JS Tag Attribute lists
 ;
 ; Product: Enterprise Web Developer (Build 906)
 ; Build Date: Wed, 28 Mar 2012 12:52:00
 ; 
 ; ----------------------------------------------------------------------------
 ; | Enterprise Web Developer for GT.M and m_apache                           |
 ; | Copyright (c) 2004-12 M/Gateway Developments Ltd,                        |
 ; | Reigate, Surrey UK.                                                      |
 ; | All rights reserved.                                                     |
 ; |                                                                          |
 ; | http://www.mgateway.com                                                  |
 ; | Email: rtweed@mgateway.com                                               |
 ; |                                                                          |
 ; | This program is free software: you can redistribute it and/or modify     |
 ; | it under the terms of the GNU Affero General Public License as           |
 ; | published by the Free Software Foundation, either version 3 of the       |
 ; | License, or (at your option) any later version.                          |
 ; |                                                                          |
 ; | This program is distributed in the hope that it will be useful,          |
 ; | but WITHOUT ANY WARRANTY; without even the implied warranty of           |
 ; | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            |
 ; | GNU Affero General Public License for more details.                      |
 ; |                                                                          |
 ; | You should have received a copy of the GNU Affero General Public License |
 ; | along with this program.  If not, see <http://www.gnu.org/licenses/>.    |
 ; ----------------------------------------------------------------------------
 ;
gridpanel ;; new Ext.grid.GridPanel
	;;animCollapse:bool
	;;autoExpandColumn
	;;autoExpandMax
	;;autoExpandMin
	;;autoHeight:bool
	;;autoShow:bool
	;;baseCls
	;;bbar:object
	;;border:bool
	;;buttonAlign
	;;buttons
	;;cls
	;;cm
	;;colModel
	;;collapseFirst:bool
	;;collapsed:bool
	;;collapsedCls:bool
	;;collapsible:bool
	;;columns:object
	;;ctCls
	;;deferRowRender:bool
	;;disableSelection:bool
	;;disabled:bool
	;;draggable:bool
	;;enableColumnHide:bool
	;;enableColumnMove:bool
	;;enableColumnResize:bool
	;;enableDragDrop:bool
	;;enableHdMenu:bool
	;;floating:bool
	;;footer:bool
	;;frame:bool
	;;header:bool
	;;headerAsText:bool
	;;height
	;;hidden:bool
	;;hideCollapseTool:bool
	;;hideHeaders:bool
	;;hideMode
	;;hideParent:bool
	;;iconCls
	;;id
	;;keys
	;;listeners:object
	;;loadMask
	;;maskDisabled:bool
	;;maxHeight
	;;minButtonWidth
	;;minColumnWidth
	;;overCls
	;;pageX
	;;pageY
	;;plugins:ref
	;;renderTo
	;;selModel
	;;shadow
	;;shadowOffset
	;;shim:bool
	;;sm
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;store:object
	;;stripeRows:bool
	;;style
	;;tabTip
	;;tbar
	;;title
	;;titleCollapse:bool
	;;tools
	;;trackMouseOver:bool
	;;view
	;;viewConfig:object
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
gridviewconfig ;;
	;;autoFill:bool
	;;scrollOffset
	;;***END***
gridcolumnmodel ;;
	;;id
	;;***END***
gridcolumn ;;
	;;align
	;;css
	;;dataIndex
	;;editor:object
	;;fixed:bool
	;;header
	;;hidden:bool
	;;hideable:bool
	;;id
	;;listeners:object
	;;menuDisabled:bool
	;;renderer:ref
	;;resizable:bool
	;;sortable:bool
	;;tooltip
	;;width
	;;***END***
gridrowexpander ;; new Ext.grid.RowExpander
	;;tpl:object
	;;***END***
gridcheckcolumn ;; new Ext.grid.CheckColumn
	;;dataIndex
	;;header
	;;id
	;;menuDisabled:bool
	;;width
	;;***END***
grideditor ;; new Ext.grid.GridEditor
	;;id
	;;***END*** 
editorgridpanel ;; new Ext.grid.EditorGridPanel
	;;animCollapse:bool
	;;autoEncode:bool
	;;autoExpandColumn
	;;autoExpandMax
	;;autoExpandMin
	;;autoHeight:bool
	;;autoShow:bool
	;;baseCls
	;;bbar:object
	;;border:bool
	;;buttonAlign
	;;buttons
	;;clicksToEdit
	;;cls
	;;cm
	;;colModel
	;;collapseFirst:bool
	;;collapsed:bool
	;;collapsedCls:bool
	;;collapsible:bool
	;;columns:object
	;;ctCls
	;;deferRowRender:bool
	;;disableSelection:bool
	;;disabled:bool
	;;draggable:bool
	;;enableColumnHide:bool
	;;enableColumnMove:bool
	;;enableColumnResize:bool
	;;enableDragDrop:bool
	;;enableHdMenu:bool
	;;floating:bool
	;;footer:bool
	;;frame:bool
	;;header:bool
	;;headerAsText:bool
	;;height
	;;hidden:bool
	;;hideCollapseTool:bool
	;;hideHeaders:bool
	;;hideMode
	;;hideParent:bool
	;;iconCls
	;;id
	;;keys
	;;listeners:object
	;;loadMask
	;;maskDisabled:bool
	;;maxHeight
	;;minButtonWidth
	;;minColumnWidth
	;;overCls
	;;pageX
	;;pageY
	;;plugins:ref
	;;renderTo
	;;selModel
	;;shadow
	;;shadowOffset
	;;shim:bool
	;;sm
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;store:object
	;;stripeRows:bool
	;;style
	;;tabTip
	;;tbar
	;;title
	;;titleCollapse:bool
	;;tools
	;;view
	;;viewConfig:object
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
template ;; new Ext.Template
	;;***END***
itemselector ;; new Ext.ux.ItemSelector
	;;dataFields:ref
	;;displayField
	;;fieldLabel
	;;fromData:ref
	;;fromStore:object
	;;fromLegend
	;;hideLabel:bool
	;;hiddenName
	;;id
	;;imagePath
	;;msWidth
	;;msHeight
	;;name
	;;toData:ref
	;;toLegend
	;;toStore:object
	;;toTBar
	;;valueField
	;;***END***
triggerfield ;; new Ext.form.TriggerField
	;;allowBlank:bool
	;;allowDomMove:bool
	;;applyTo:bool
	;;autoCreate
	;;autoShow:bool
	;;blankText
	;;clearCls
	;;cls
	;;ctCls
	;;disableKeyFilter:bool
	;;disabled:bool
	;;disabledClass
	;;emptyClass
	;;emptyText
	;;fieldClass
	;;fieldLabel
	;;focusClass
	;;height
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;hideTrigger:bool
	;;id
	;;inputType
	;;invalidClass
	;;invalidText
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;maskRe
	;;maxLength
	;;maxLengthText
	;;minLength
	;;minLengthText
	;;msgFx
	;;msgTarget
	;;name
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;readOnly:bool
	;;regex
	;;regexText
	;;renderTo
	;;selectOnFocus:bool
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;triggerClass
	;;validateOnBlur
	;;validationDelay
	;;validationEvent
	;;validator
	;;value
	;;vtype
	;;vtypetext
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
formlabel ;; new Ext.form.Label
	;;allowBlank:bool
	;;anchor
	;;applyTo:bool
	;;autoEl
	;;autoHeight:bool
	;;autoShow:bool
	;;autoWidth
	;;cls
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;forId
	;;height
	;;hidden:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;id
	;;listeners:object
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;text
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
progressbar ;; new Ext.ProgressBar
	;;allowDomMove:bool
	;;applyTo
	;;autoEl
	;;autoHeight:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;baseCls
	;;cls
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;height
	;;hidden:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;listeners:object
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;text
	;;textEl
	;;value
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
statusbar ;; new Ext.StatusBar
	;;allowDomMove:bool
	;;applyTo
	;;autoClear
	;;autoHeight:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;busyIconCls
	;;busyText
	;;baseCls
	;;cls
	;;ctCls
	;;defaultIconCls
	;;defaultText
	;;disabled:bool
	;;disabledClass
	;;height
	;;hidden:bool
	;;hideMode
	;;hideParent:bool
	;;iconCls
	;;id
	;;listeners:object
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;statusAlign
	;;style
	;;text
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
