%zewdExtJSData	; Ext-JS Tag Attribute lists
 ;
 ; Product: Enterprise Web Developer (Build 910)
 ; Build Date: Wed, 25 Apr 2012 17:59:25
 ; 
 ; ----------------------------------------------------------------------------
 ; | Enterprise Web Developer for GT.M and m_apache                           |
 ; | Copyright (c) 2004-12 M/Gateway Developments Ltd,                        |
 ; | Reigate, Surrey UK.                                                      |
 ; | All rights reserved.                                                     |
 ; |                                                                          |
 ; | http://www.mgateway.com                                                  |
 ; | Email: rtweed@mgateway.com                                               |
 ; |                                                                          |
 ; | This program is free software: you can redistribute it and/or modify     |
 ; | it under the terms of the GNU Affero General Public License as           |
 ; | published by the Free Software Foundation, either version 3 of the       |
 ; | License, or (at your option) any later version.                          |
 ; |                                                                          |
 ; | This program is distributed in the hope that it will be useful,          |
 ; | but WITHOUT ANY WARRANTY; without even the implied warranty of           |
 ; | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            |
 ; | GNU Affero General Public License for more details.                      |
 ; |                                                                          |
 ; | You should have received a copy of the GNU Affero General Public License |
 ; | along with this program.  If not, see <http://www.gnu.org/licenses/>.    |
 ; ----------------------------------------------------------------------------
 ;
datastore ;; new Ext.data.Store
	;;data:ref
	;;reader:object
	;;***END***
dataarrayreader ;; new Ext.data.ArrayReader
	;;id
	;;***END***
dataarrayreaderrecord ;;
	;;dateFormat
	;;name
	;;type
	;;***END***
listeners ;;
	;;***END***
combobox ;; new Ext.form.ComboBox
	;;allQuery
	;;allowBlank:bool
	;;allowDomMove:bool
	;;applyTo
	;;autoCreate:bool
	;;autoShow:bool
	;;blankText
	;;clearCls
	;;cls
	;;ctCls
	;;disableKeyFilter:bool
	;;disabled:bool
	;;disabledClass
	;;displayField
	;;editable:bool
	;;emptyClass
	;;emptyText
	;;fieldClass
	;;fieldLabel
	;;focusClass
	;;forceSelection:bool
	;;handleHeight
	;;height
	;;hidden:bool
	;;hiddenId
	;;hiddenName
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;hideTrigger:bool
	;;id
	;;inputType
	;;invalidClass
	;;invalidText
	;;itemCls
	;;itemSelector
	;;labelSeparator
	;;labelStyle
	;;lazyInit:bool
	;;lazyRender:bool
	;;listAlign
	;;listClass
	;;listWidth
	;;listeners:object
	;;loadingText
	;;maskRe
	;;maxHeight
	;;maxLength
	;;maxLengthText
	;;minChars
	;;minHeight
	;;minLength
	;;minLengthText
	;;minListWidth
	;;mode
	;;msgFx
	;;msgTarget
	;;name
	;;overCls
	;;pageSize
	;;pageX
	;;pageY
	;;plugins
	;;queryDelay
	;;queryParam
	;;readOnly:bool
	;;regex
	;;regexText
	;;renderTo
	;;resizable:bool
	;;selectOnFocus:bool
	;;selectedClass
	;;shadow:bool
	;;stateEvents
	;;stateId
	;;stateful
	;;store:ref
	;;style
	;;tabIndex
	;;title
	;;tpl
	;;transform
	;;triggerAction
	;;triggerClass
	;;typeAhead:bool
	;;typeAheadDelay
	;;validateOnBlur
	;;validationDelay
	;;validationEvent
	;;validator
	;;value
	;;valueField
	;;valueNotFoundText
	;;vtype
	;;vtypeText
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
htmleditor ;; new Ext.form.HtmlEditor
	;;autoShow:bool
	;;clearCls
	;;createLinkText
	;;ctCls
	;;defaultLinkValue
	;;enableAlignments:bool
	;;enableColors:bool
	;;enableFont:bool
	;;enableFontSize:bool
	;;enableFormat:bool
	;;enableLinks:bool
	;;enableLists:bool
	;;enableSourceEdit:bool
	;;fieldLabel
	;;fontFamilies
	;;height
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;name
	;;pageX
	;;pageY
	;;plugins
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;value
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
menu ;; new Ext.menu.Menu
	;;allowOtherMenus:bool
	;;defaultAlign
	;;defaults
	;;ignoreParentClicks
	;;items:array
	;;listeners:object
	;;minWidth
	;;shadow
	;;subMenuAlign
	;;***END*** 
menuitem ;; new Ext.menu.Item
	;;activeClass
	;;allowDomMove:bool
	;;applyTo
	;;autoEl
	;;autoShow:bool
	;;canActivate:bool
	;;cls
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;handler:object
	;;hidden:bool
	;;hideDelay
	;;hideMode
	;;hideOnClick:bool
	;;hideParent:bool
	;;href
	;;hrefTarget
	;;icon
	;;iconCls
	;;id
	;;itemCls
	;;listeners:object
	;;menu:object
	;;overCls
	;;plugins
	;;renderTo
	;;scope
	;;showDelay
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;text
	;;xtype
	;;***END*** 
checkitem ;; new Ext.menu.CheckItem
	;;activeClass
	;;allowDomMove:bool
	;;applyTo
	;;autoEl
	;;autoShow:bool
	;;canActivate:bool
	;;checked:bool
	;;checkHandler:object
	;;cls
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;group
	;;groupClass
	;;handler:object
	;;hidden:bool
	;;hideDelay
	;;hideMode
	;;hideOnClick:bool
	;;hideParent:bool
	;;href
	;;hrefTarget
	;;icon
	;;iconCls
	;;id
	;;itemCls
	;;listeners:object
	;;menu:object
	;;overCls
	;;plugins
	;;renderTo
	;;scope
	;;showDelay
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;text
	;;xtype
	;;***END*** 
menuseparator ;; new Ext.menu.Separator
	;;activeClass
	;;allowDomMove:bool
	;;applyTo
	;;autoEl
	;;autoShow:bool
	;;canActivate:bool
	;;cls
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;handler:object
	;;hidden:bool
	;;hideDelay
	;;hideMode
	;;hideOnClick:bool
	;;hideParent:bool
	;;id
	;;itemCls
	;;listeners:object
	;;overCls
	;;plugins
	;;renderTo
	;;scope
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;xtype
	;;***END*** 
menutextitem ;; new Ext.menu.TextItem
	;;activeClass
	;;allowDomMove:bool
	;;applyTo
	;;autoEl
	;;autoShow:bool
	;;canActivate:bool
	;;cls
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;handler:object
	;;hidden:bool
	;;hideDelay
	;;hideMode
	;;hideOnClick:bool
	;;hideParent:bool
	;;id
	;;itemCls
	;;listeners:object
	;;overCls
	;;plugins
	;;renderTo
	;;scope
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;text
	;;xtype
	;;***END*** 
columnlayout ;; new Ext.layout.ColumnLayout
	;;extraCls
	;;renderHidden:bool
	;;***END*** 
checkbox ;; new Ext.form.Checkbox
	;;allowDomMove:bool
	;;applyTo:bool
	;;autoCreate:bool
	;;autoShow:bool
	;;boxLabel
	;;checked:bool
	;;checkedCls
	;;clearCls
	;;cls
	;;ctCls
	;;disabled:bool
	;;fieldClass
	;;fieldLabel
	;;focusCls
	;;handler
	;;height
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;inputType
	;;inputValue
	;;invalidClass
	;;invalidText
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;mouseDownCls
	;;msgFx
	;;msgTarget
	;;name
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;readOnly:bool
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;validateOnBlur:bool
	;;validationDelay
	;;validationEvent
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
checkboxgroup ;; new Ext.form.CheckboxGroup
	;;allowBlank:bool
	;;allowDomMove:bool
	;;applyTo:bool
	;;autoCreate:bool
	;;autoShow:bool
	;;blankText
	;;clearCls
	;;cls
	;;columns
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;fieldClass
	;;fieldLabel
	;;focusClass
	;;height
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;inputType
	;;invalidClass
	;;invalidText
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;msgFx
	;;msgTarget
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;readOnly:bool
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;validateOnBlur:bool
	;;validationDelay
	;;validationEvent
	;;value
	;;vertical:bool
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
radio ;; new Ext.form.Radio
	;;allowDomMove:bool
	;;applyTo:bool
	;;autoCreate:bool
	;;autoShow:bool
	;;boxLabel
	;;checked:bool
	;;checkedCls
	;;clearCls
	;;cls
	;;ctCls
	;;disabled:bool
	;;fieldClass
	;;fieldLabel
	;;focusCls
	;;handler
	;;height
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;inputType
	;;inputValue
	;;invalidClass
	;;invalidText
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;mouseDownCls
	;;msgFx
	;;msgTarget
	;;name
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;readOnly:bool
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;validateOnBlur:bool
	;;validationDelay
	;;validationEvent
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
radiogroup ;; new Ext.form.RadioGroup
	;;allowBlank:bool
	;;allowDomMove:bool
	;;applyTo:bool
	;;autoCreate:bool
	;;autoShow:bool
	;;blankText
	;;clearCls
	;;cls
	;;columns
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;fieldClass
	;;fieldLabel
	;;focusClass
	;;height
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;inputType
	;;invalidClass
	;;invalidText
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;msgFx
	;;msgTarget
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;readOnly:bool
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;validateOnBlur:bool
	;;validationDelay
	;;validationEvent
	;;value
	;;vertical:bool
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
timefield ;; new Ext.form.TimeField
	;;allQuery
	;;allowBlank:bool
	;;allowDomMove:bool
	;;allFormats
	;;applyTo:bool
	;;autoCreate:bool
	;;autoShow:bool
	;;blankText
	;;clearCls
	;;cls
	;;ctCls
	;;disableKeyFilter:bool
	;;disabled:bool
	;;disabledClass
	;;displayField
	;;editable
	;;emptyClass
	;;emptyText
	;;fieldClass
	;;fieldLabel
	;;focusClass
	;;forceSelection:bool
	;;format
	;;handleHeight
	;;height
	;;hidden:bool
	;;hiddenId
	;;hiddenName
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;hideTrigger:bool
	;;id
	;;increment
	;;inputType
	;;invalidClass
	;;invalidText
	;;itemCls
	;;itemSelector
	;;labelSeparator
	;;labelStyle
	;;lazyInit:bool
	;;lazyRender:bool
	;;listAlign
	;;listClass
	;;listWidth
	;;listeners:object
	;;loadingText
	;;maskRe
	;;maxHeight
	;;maxLength
	;;maxLengthText
	;;maxText
	;;maxValue
	;;minChars
	;;minHeight
	;;minLength
	;;minLengthText
	;;minListWidth
	;;minText
	;;minValue
	;;mode
	;;msgFx
	;;msgTarget
	;;name
	;;overCls
	;;pageSize
	;;pageX
	;;pageY
	;;plugins
	;;queryDelay
	;;queryparam
	;;readOnly:bool
	;;regex
	;;regexText
	;;renderTo
	;;resizable
	;;selectOnFocus
	;;selectedClass
	;;shadow
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;store
	;;style
	;;tabIndex
	;;title
	;;tpl
	;;transform
	;;triggerAction
	;;triggerClass
	;;typeAhead:bool
	;;typeAheadDelay
	;;validateOnBlur:bool
	;;validationDelay
	;;validationEvent
	;;validator
	;;valueNotFoundText
	;;value
	;;valueField
	;;vtype
	;;vtypeText
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
datefield ;; new Ext.form.DateField
	;;allowBlank:bool
	;;allowDomMove:bool
	;;allFormats
	;;applyTo:bool
	;;autoCreate:bool
	;;autoShow:bool
	;;blankText
	;;clearCls
	;;cls
	;;ctCls
	;;disableKeyFilter:bool
	;;disabled:bool
	;;disabledClass
	;;disabledDates
	;;disabledDatesText
	;;disabledDays
	;;disabledDaysText
	;;emptyClass
	;;emptyText
	;;fieldClass
	;;fieldLabel
	;;focusClass
	;;format
	;;height
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;hideTrigger:bool
	;;id
	;;inputType
	;;invalidClass
	;;invalidText
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;maskRe
	;;maxLength
	;;maxLengthText
	;;maxText
	;;maxValue
	;;minLength
	;;minLengthText
	;;minText
	;;minValue
	;;msgFx
	;;msgTarget
	;;name
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;readOnly:bool
	;;regex
	;;regexText
	;;renderTo
	;;selectOnFocus
	;;showToday:bool
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;triggerClass
	;;validateOnBlur:bool
	;;validationDelay
	;;validationEvent
	;;validator
	;;value
	;;vtype
	;;vtypeText
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
numberfield ;; new Ext.form.NumberField
	;;allowBlank:bool
	;;allowDecimals:bool
	;;allowDomMove:bool
	;;allowNegative:bool
	;;applyTo:ref
	;;autoCreate:ref
	;;autoShow:bool
	;;baseChars
	;;blankText
	;;clearCls
	;;cls
	;;ctCls
	;;decimalPrecision
	;;decimalSeparator
	;;disableKeyFilter:bool
	;;disabled:bool
	;;disabledClass
	;;emptyClass
	;;emptyText
	;;fieldClass
	;;fieldLabel
	;;focusClass
	;;grow:bool
	;;growMax
	;;growMin
	;;height
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;inputType
	;;invalidClass
	;;invalidText
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;maskRe
	;;maxLength
	;;maxLengthText
	;;maxText
	;;maxValue
	;;minLength
	;;minLengthText
	;;minText
	;;minValue
	;;msgFx
	;;msgTarget
	;;name
	;;nanText
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;readOnly:bool
	;;regex
	;;regexText
	;;renderTo
	;;selectOnFocus
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;validateOnBlur:bool
	;;validationDelay
	;;validationEvent
	;;validator
	;;value
	;;vtype
	;;vtypeText
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
hiddenfield ;; new Ext.form.Hidden
	;;allowDomMove:bool
	;;applyTo:bool
	;;autoCreate:bool
	;;autoShow:bool
	;;clearCls
	;;cls
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;fieldClass
	;;fieldLabel
	;;focusClass
	;;height
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;inputType
	;;invalidClass
	;;invalidText
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;msgFx
	;;msgTarget
	;;name
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;readOnly:bool
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;validateOnBlur:bool
	;;validationDelay
	;;validationEvent
	;;value
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
textfield ;; new Ext.form.TextField
	;;allowBlank:bool
	;;allowDomMove:bool
	;;anchor
	;;applyTo:bool
	;;autoCreate:bool
	;;autoShow:bool
	;;blankText
	;;clearCls
	;;cls
	;;ctCls
	;;disableKeyFilter:bool
	;;disabled:bool
	;;disabledClass
	;;emptyClass
	;;emptyText
	;;fieldClass
	;;fieldLabel
	;;focusClass
	;;grow:bool
	;;growMax
	;;growMin
	;;height
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;inputType
	;;invalidClass
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;maskRe
	;;maxLength
	;;maxLengthText
	;;minLength
	;;minLengthText
	;;msgFx
	;;msgTarget
	;;name
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;readOnly:bool
	;;regex
	;;regexText
	;;renderTo
	;;selectOnFocus
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;validateOnBlur:bool
	;;validationDelay
	;;validationEvent
	;;validator
	;;value
	;;vtype
	;;vtypeText
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
textarea ;; new Ext.form.TextArea
	;;allowBlank:bool
	;;allowDomMove:bool
	;;applyTo:bool
	;;autoCreate:bool
	;;autoShow:bool
	;;blankText
	;;clearCls
	;;cls
	;;ctCls
	;;disableKeyFilter:bool
	;;disabled:bool
	;;disabledClass
	;;emptyClass
	;;emptyText
	;;fieldClass
	;;fieldLabel
	;;focusClass
	;;grow:bool
	;;growMax
	;;growMin
	;;height
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;id
	;;inputType
	;;invalidClass
	;;invalidText
	;;itemCls
	;;labelSeparator
	;;labelStyle
	;;listeners:object
	;;maskRe
	;;maxLength
	;;maxLengthText
	;;minLength
	;;minLengthText
	;;msgFx
	;;msgTarget
	;;name
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;preventScrollbars:bool
	;;readOnly:bool
	;;regex
	;;regexText
	;;renderTo
	;;selectOnFocus
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;validateOnBlur:bool
	;;validationDelay
	;;validationEvent
	;;validator
	;;value
	;;vtype
	;;vtypeText
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
fieldset ;; new Ext.form.FieldSet
	;;allowDomMove:bool
	;;animCollapse:bool
	;;autoDestroy:bool
	;;autoHeight:bool
	;;autoLoad
	;;autoScroll:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;baseCls
	;;bodyStyle
	;;checkboxName
	;;checkboxToggle
	;;cls
	;;collapsed:bool
	;;collapsedCls
	;;collapsible:bool
	;;contentEl
	;;ctCls
	;;defaults
	;;disabled:bool
	;;draggable
	;;height
	;;hidden:bool
	;;hideBorders:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;id
	;;itemCls
	;;keys
	;;labelWidth
	;;layout
	;;layoutConfig:object
	;;listeners:object
	;;maskDisabled:bool
	;;minButtonWidth
	;;monitorResize:bool
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabTip
	;;title
	;;width
	;;x
	;;y
	;;***END*** 
button ;; new Ext.Button
	;;anchor
	;;allowDepress:bool
	;;allowDomMove:bool
	;;applyTo
	;;autoShow:bool
	;;clickEvent
	;;cls
	;;ctCls
	;;disabled:bool
	;;disableClass
	;;enableToggle:bool
	;;handleMouseEvents:bool
	;;handler: function()
	;;hidden:bool
	;;hideLabel:bool
	;;hideMode
	;;hideParent:bool
	;;icon
	;;iconCls
	;;id
	;;isFormField:bool
	;;listeners:object
	;;menu
	;;menuAlign
	;;midWidth
	;;overCls
	;;plugins
	;;pressed:bool
	;;renderTo
	;;repeat:bool
	;;scope
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;template
	;;text
	;;toggleGroup
	;;toggleHandler
	;;tooltip
	;;tooltipType
	;;type
	;;xtype
	;;***END***
layoutconfig ;;
	;;activeOnTop:bool
	;;animate:bool
	;;autoWidth:bool
	;;collapseFirst:bool
	;;extraCls
	;;fill:bool
	;;hideCollapseTool:bool
	;;renderHidden:bool
	;;sequence:bool
	;;titleCollapse:bool
	;;***END***
formsubmit ;;
	;;url
	;;waitMsg
	;;success:function(form,action)
	;;failure:function(form,action)
	;;***END***
formpanel ;; new Ext.form.FormPanel
	;;activeItem
	;;allowDomMove:bool
	;;animCollapse:bool
	;;applyTo
	;;autoDestroy:bool
	;;autoHeight:bool
	;;autoLoad
	;;autoScroll:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;baseCls
	;;bbar:object
	;;bodyBorder:bool
	;;bodyStyle
	;;border:bool
	;;bufferResize
	;;buttonAlign
	;;buttons:array
	;;cls
	;;collapseFirst:bool
	;;collapsed:bool
	;;collapsedCls
	;;collapsible:bool
	;;contentEl
	;;ctCls
	;;defaultType
	;;defaults
	;;disabled:bool
	;;disabledClass
	;;draggable
	;;elements
	;;floating:bool
	;;footer:bool
	;;formId
	;;frame:bool
	;;header:bool
	;;headerAsText:bool
	;;height
	;;hidden:bool
	;;hideBorders:bool
	;;hideCollapseTool:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;iconCls
	;;id
	;;itemCls
	;;keys
	;;labelAlign
	;;labelWidth
	;;layoutConfig:object
	;;listeners:object
	;;maskDisabled:bool
	;;minButtonWidth
	;;monitorPoll
	;;monitorResize:bool
	;;monitorValid:bool
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;renderTo
	;;shadow
	;;shadowOffset
	;;shim:bool
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabTip
	;;tbar
	;;title
	;;titleCollapse:bool
	;;tools
	;;width
	;;x
	;;xtype
	;;y
	;;***END*** 
panel ;; new Ext.Panel
	;;activeItem
	;;allowDomMove:bool
	;;animCollapse:bool
	;;applyTo
	;;autoDestroy:bool
	;;autoHeight:bool
	;;autoLoad
	;;autoScroll:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;baseCls
	;;bbar:object
	;;bodyBorder:bool
	;;bodyCfg:ref
	;;bodyStyle
	;;border:bool
	;;bufferResize
	;;buttonAlign
	;;buttons
	;;cls
	;;collapseFirst:bool
	;;collapsed:bool
	;;collapsedCls
	;;collapseMode
	;;collapsible:bool
	;;columnWidth
	;;contentEl
	;;ctCls
	;;defaultType
	;;defaults
	;;disabledClass
	;;draggable
	;;el
	;;elements
	;;floating:bool
	;;footer:bool
	;;frame:bool
	;;header:bool
	;;headerAsText:bool
	;;height
	;;hidden:bool
	;;hideBorders:bool
	;;hideCollapseTool:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;iconCls
	;;id
	;;items
	;;keys
	;;layout
	;;layoutConfig:object
	;;listeners:object
	;;margins
	;;maskDisabled:bool
	;;minButtonWidth
	;;minHeight
	;;minWidth
	;;monitorResize
	;;plugins
	;;region
	;;renderTo
	;;shadow
	;;shadowOffset
	;;shim:bool
	;;split:bool
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabTip
	;;tbar
	;;title
	;;titleCollapse:bool
	;;tools
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
tabpanel ;; new Ext.TabPanel
	;;activeItem
	;;activeTab
	;;allowDomMove:bool
	;;animCollapse:bool
	;;animScroll:bool
	;;applyTo
	;;autoDestroy:bool
	;;autoHeight:bool
	;;autoLoad
	;;autoScroll:bool
	;;autoShow:bool
	;;autoTabSelector
	;;autoTabs:bool
	;;autoWidth:bool
	;;baseCls
	;;bbar:object
	;;bodyBorder:bool
	;;bodyStyle
	;;border:bool
	;;bufferResize:bool
	;;buttonAlign
	;;buttons
	;;cls
	;;collapseFirst:bool
	;;collapsedCls
	;;contentEl
	;;ctCls
	;;defaultType
	;;defaults
	;;deferredRender:bool
	;;disabledClass
	;;draggable:bool
	;;elements
	;;enableTabScroll:bool
	;;floating:bool
	;;footer:bool
	;;frame:bool
	;;height
	;;hidden:bool
	;;hideBorders:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;iconCls
	;;id
	;;items:array
	;;keys
	;;layoutOnTabChange:bool
	;;listeners:object
	;;maskDisabled:bool
	;;minButtonWidth
	;;minTabWidth
	;;monitorResize:bool
	;;overCls
	;;pageX
	;;pageY
	;;plain:bool
	;;plugins
	;;region
	;;renderTo
	;;resizeTabs:bool
	;;scrollDuration
	;;scrollIncrement
	;;scrollRepeatInterval
	;;shadow:bool
	;;shadowOffset
	;;shim:bool
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabMargin
	;;tabPosition
	;;tabTip
	;;tabWidth
	;;tbar
	;;title
	;;wheelIncrement
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
toolbar ;; new Ext.Toolbar
	;;allowDOMMove:bool
	;;applyTo
	;;autoHeight:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;cls
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;height
	;;hidden:bool
	;;hideMode
	;;hideParent
	;;id
	;;items:array
	;;listeners:object
	;;pageX
	;;pageY
	;;plugins
	;;renderTo
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
toolbarfill ;; new Ext.Toolbar.Fill
	;;id
	;;***END***
toolbarspacer ;; new Ext.Toolbar.Spacer
	;;id
	;;***END***
toolbarseparator ;; new Ext.Toolbar.Separator
	;;id
	;;***END***
toolbartextitem ;; new Ext.Toolbar.TextItem
	;;text
	;;***END***
toolbarbutton ;; new Ext.Toolbar.Button
	;;allowDepress:bool
	;;allowDOMMove:bool
	;;applyTo
	;;autoShow:bool
	;;clickEvent
	;;cls
	;;ctCls
	;;disabled:bool
	;;disabledClass
	;;enableToggle:bool
	;;handleMouseEvents:bool
	;;handler:object
	;;hidden:bool
	;;hideMode
	;;hideParent:bool
	;;icon
	;;iconCls
	;;id
	;;listeners:object
	;;menu:object
	;;menuAlign
	;;minWidth
	;;overCls
	;;plugins
	;;pressed:bool
	;;renderTo
	;;repeat:bool
	;;scope
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabIndex
	;;template
	;;text
	;;toggleGroup
	;;toggleHandler
	;;tooltip
	;;tooltipType
	;;type
	;;xtype
	;;***END***
viewport ;; new Ext.Viewport
	;;activeItem
	;;autoDestroy:bool
	;;autoEl
	;;autoShow:bool
	;;bufferResize:bool
	;;cls
	;;ctCls
	;;defaultType
	;;defaults
	;;disabled:bool
	;;disabledClass
	;;hidden:bool
	;;hideBorders:bool
	;;hideMode
	;;id
	;;items
	;;layout
	;;layoutConfig:object
	;;listeners:object
	;;monitorResize:bool
	;;overCls
	;;pageX
	;;pageY
	;;plugins
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;x
	;;xtype
	;;y
	;;***END***
store
	;;autoLoad:bool
	;;data
	;;baseParams
	;;listeners:object
	;;proxy
	;;pruneModifiedRecords:bool
	;;reader
	;;remoteSort:bool
	;;sortInfo
	;;storeId
	;;url
	;;***END***
window ;; new Ext.Window
	;;activeItem
	;;allowDOMMove:bool
	;;animCollapse:bool
	;;animateTarget:bool
	;;applyTo
	;;autoDestroy:bool
	;;autoHeight:bool
	;;autoLoad
	;;autoScroll:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;baseCls
	;;bbar:object
	;;bodyBorder:bool
	;;bodyStyle
	;;border:bool
	;;bufferResize:bool
	;;buttonAlign
	;;buttons
	;;closable
	;;closeAction
	;;cls
	;;collapseFirst
	;;collapsed:bool
	;;collapsedCls
	;;collapsible:bool
	;;constrain:bool
	;;constrainHeader:bool
	;;contentEl
	;;ctCls
	;;defaultType
	;;defaults
	;;disabledClass
	;;draggable:bool
	;;expandOnShow:bool
	;;footer:bool
	;;header:bool
	;;headerAsText:bool
	;;height
	;;hideBorders:bool
	;;hideCollapseTool:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;iconCls
	;;id
	;;items
	;;keys
	;;layout
	;;layoutConfig:object
	;;listeners:object
	;;manager
	;;maskDisabled:bool
	;;maximizable:bool
	;;minButtonWidth
	;;minHeight
	;;minWidth
	;;minimizable:bool
	;;modal:bool
	;;onEsc
	;;pageX
	;;pageY
	;;plain:bool
	;;plugins
	;;renderTo
	;;resizable:bool
	;;resizeHandles
	;;shadow:bool
	;;shadowOffset
	;;shim:bool
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabTip
	;;tbar
	;;title
	;;titleCollapse:bool
	;;tools
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
modalwindow ;;
	;;activeItem
	;;allowDOMMove:bool
	;;animCollapse:bool
	;;animateTarget:bool
	;;applyTo
	;;autoDestroy:bool
	;;autoHeight:bool
	;;autoLoad
	;;autoScroll:bool
	;;autoShow:bool
	;;autoWidth:bool
	;;baseCls
	;;bbar:object
	;;bodyBorder:bool
	;;bodyStyle
	;;border:bool
	;;bufferResize:bool
	;;buttonAlign
	;;buttons
	;;closable
	;;closeAction
	;;cls
	;;collapseFirst
	;;collapsed:bool
	;;collapsedCls
	;;collapsible:bool
	;;constrain:bool
	;;constrainHeader:bool
	;;contentEl
	;;ctCls
	;;currentPageName
	;;defaultType
	;;defaults
	;;disabledClass
	;;draggable:bool
	;;expandOnShow:bool
	;;footer:bool
	;;header:bool
	;;headerAsText:bool
	;;height
	;;hideBorders:bool
	;;hideCollapseTool:bool
	;;hideMode
	;;hideParent:bool
	;;html
	;;iconCls
	;;id
	;;items
	;;keys
	;;layout
	;;layoutConfig:object
	;;listeners:object
	;;manager
	;;maskDisabled:bool
	;;maximizable:bool
	;;minButtonWidth
	;;minHeight
	;;minWidth
	;;minimizable:bool
	;;modal:bool
	;;onEsc
	;;pageX
	;;pageY
	;;plain:bool
	;;plugins
	;;renderTo
	;;resizable:bool
	;;resizeHandles
	;;shadow:bool
	;;shadowOffset
	;;shim:bool
	;;src
	;;stateEvents
	;;stateId
	;;stateful:bool
	;;style
	;;tabTip
	;;tbar
	;;title
	;;titleCollapse:bool
	;;tools
	;;width
	;;x
	;;xtype
	;;y
	;;***END***
